sources: lib/**/*.rb
lints:
  InstanceVariables:
    limit: 1
  LineRestriction:
    limit: 87
  DemeterLaw:
    exclude:
      - 'IceNine::Freezer'
  ElseClauses:
    exclude:
      - 'IceNine::Freezer'
